import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { RecoilRoot } from "recoil";
import BoxPlane from "../components/BoxPlane";
import CanvasPlane from "../components/CanvasPlane";
import OuterPlane from "../components/OuterPlane";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <RecoilRoot>
                    <div className="relative h-screen">
                        <OuterPlane />
                        <BoxPlane />
                        <CanvasPlane />
                    </div>
                </RecoilRoot>
            </main>

            <footer className="absolute bottom-4 left-2">
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home
